### ISSUE TITLE
Copyright statement?

### ISSUE THREAD

**Issue by filippog** [knyar/phalerts#3]
Hi,
thank you for phalerts! I'm trying it out and was wondering who's the copyright holder? I couldn't find any statement in the source.

thank you!
Filippo

**Comment by knyar** [comment]
Hi! Copyright law might differ between various countries, and I am not a lawyer, so I don't think I can provide a confident answer to this question.

I am the author of most (but not all) of the source code; you can take a look at `git blame` to see an author of a particular line. As documented in README, the code has been licensed under the MIT license.

I hope this helps.

**Comment by filippog** [comment]
Thank you, it does! What I'm looking for is also the possibility of adding "copyright <year> <name>" to the source files, is that something you are willing to consider?

thanks!

**Comment by knyar** [comment]
I've added a few lines to the source code based on [some recommendations](https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/) I read online.
