### ISSUE TITLE
Support for passing PHIDs ?

### ISSUE THREAD

**Issue by filippog** [knyar/phalerts#4]
Hi,
thank you again for phalerts! I'd like to be able to pass PHIDs as well as project names; the main reason being that projects can get renamed but PHIDs stay the same. Is that something you are interested in? e.g. supporting `phid` on the query string. I'm happy to help with a PR, but wanted to gauge interest first.

**Comment by knyar** [comment]
Sure, I will be happy to review a PR adding this. Thanks!
