### ISSUE TITLE
Override task title template from url?

### ISSUE THREAD

**Issue by filippog** [knyar/phalerts#6]
Hello,
thank you for phalerts! Super useful and works well. We're running into a situation where the default `tpl_title` of `{{ groupLabels.alertname }}` is fine for most alerts, but not all. Specifically for network devices alerts we want to group tasks by device (e.g. in `instance` label) whereas normally task grouped by alertname make sense and it is what we want.

I was thinking a possible solution would be giving users the ability to override the template via query string arguments, e.g. `/alerts?project=foo&tpl_title={{ ... }}` (not escaped but you get the idea). What do you think ? I'm happy to contribute a PR and wanted to share/discuss first. Thank you !

**Comment by knyar** [comment]
Hi! I am glad you found this tool useful :)

Allowing `tpl_title` to be overridden via a URL parameter sounds like a good idea. I will be glad to review your PR if you decide to submit one. Thank you!

**Comment by filippog** [comment]
Fantastic, thank you for the feedback! I'll be following up with a PR (timeline TBD)
